# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# https://go.microsoft.com/fwlink/?LinkID=512686

# Builds the library and test suite.

schedules:
  - cron: "30 6 * * *"
    displayName: 'Nightly build'
    branches:
      include:
        - main

# GitHub Actions handles test suite for CI/PR
trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - '.azuredevops/pipelines/UVAtlas-GitHub-Test.yml'

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: dxMeshRepo
      name: Microsoft/DirectXMesh
      type: github
      endpoint: microsoft
      ref: refs/heads/main
    - repository: dxTexRepo
      name: Microsoft/DirectXTex
      type: github
      endpoint: microsoft
      ref: refs/heads/main
    - repository: testRepo
      name: walbourn/uvatlastest
      type: github
      endpoint: microsoft
      ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: windows-2022

variables:
  Codeql.Enabled: false

jobs:
  - job: DESKTOP_BUILD
    displayName: 'Windows Desktop'
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 1
    workspace:
      clean: all
    strategy:
      maxParallel: 2
      matrix:
        Release_x64:
          BuildPlatform: x64
          BuildConfiguration: Release
        Debug_x64:
          BuildPlatform: x64
          BuildConfiguration: Debug
        Release_x86:
          BuildPlatform: x86
          BuildConfiguration: Release
        Debug_x86:
          BuildPlatform: x86
          BuildConfiguration: Debug
    steps:
      - checkout: self
        clean: true
        fetchTags: false
        path: 's/UVAtlas'
      - checkout: dxMeshRepo
        displayName: Fetch DirectXMesh
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/DirectXMesh'
      - checkout: dxTexRepo
        displayName: Fetch DirectXTex
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/DirectXTex'
      - checkout: testRepo
        displayName: Fetch Tests
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/UVAtlas/Tests'
      - task: VSBuild@1
        displayName: Build solution xtuvatlas_Desktop_2019.sln
        inputs:
          solution: UVAtlas/Tests/xtuvatlas_Desktop_2019.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
