# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=512686

name: 'CTest (Windows)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.nuget/*'
      - build/*.mdb
      - build/*.props
      - build/*.ps1
      - build/*.yml

env:
  DIRECTXMESH_MEDIA_PATH: ${{ github.workspace }}/Media
  DIRECTXMESH_TEX_PATH: ${{ github.workspace }}/Media

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        os: [windows-2019, windows-2022]
        build_type: [x64-Debug, x64-Release, x64-Debug-Clang, x64-Release-Clang]
        arch: [amd64]
        include:
          - os: windows-2019
            build_type: x86-Debug
            arch: amd64_x86
          - os: windows-2019
            build_type: x86-Release
            arch: amd64_x86
          - os: windows-2019
            build_type: x86-Debug-Clang
            arch: amd64_x86
          - os: windows-2019
            build_type: x86-Release-Clang
            arch: amd64_x86
          - os: windows-2022
            build_type: x86-Debug
            arch: amd64_x86
          - os: windows-2022
            build_type: x86-Release
            arch: amd64_x86
          - os: windows-2022
            build_type: x86-Debug-Clang
            arch: amd64_x86
          - os: windows-2022
            build_type: x86-Release-Clang
            arch: amd64_x86
          - os: windows-2022
            build_type: arm64-Debug
            arch: amd64_arm64
          - os: windows-2022
            build_type: arm64-Release
            arch: amd64_arm64
          - os: windows-2022
            build_type: arm64ec-Debug
            arch: amd64_arm64
          - os: windows-2022
            build_type: arm64ec-Release
            arch: amd64_arm64

    steps:
    - uses: actions/checkout@v4

    - name: Clone test repository
      uses: actions/checkout@v4
      with:
        repository: walbourn/uvatlastest
        path: Tests
        ref: main

    - name: 'Install Ninja'
      run: choco install ninja

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - if: matrix.arch == 'amd64'
      name: 'Set triplet x64-windows'
      shell: cmd
      run: set VCPKG_DEFAULT_TRIPLET=x64-windows

    - if: matrix.arch == 'amd64_x86'
      name: 'Set triplet x86-windows'
      shell: cmd
      run: set VCPKG_DEFAULT_TRIPLET=x86-windows

    - if: matrix.arch == 'amd64_arm64'
      name: 'Set triplet arm64-Windows'
      shell: cmd
      run: set VCPKG_DEFAULT_TRIPLET=arm64-windows

    - uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/build/vcpkg.json'
        vcpkgGitCommitId: 'cacf5994341f27e9a14a7b8724b0634b138ecb30'

    - name: 'Configure CMake'
      working-directory: ${{ github.workspace }}
      run: cmake --preset=${{ matrix.build_type }} -DBUILD_TOOLS=ON -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_MANIFEST_DIR="${{ github.workspace }}/build"

    - name: 'Build'
      working-directory: ${{ github.workspace }}
      run: cmake --build out\build\${{ matrix.build_type }}
